module itself
moira-alert/ansible-module pull request #1
Opened 2017-05-23 01:44 UTC by kamaev

2017-05-23 12:35 UTC, AlexAkulov commented
- У нас есть клиент на питоне, https://github.com/moira-alert/python-moira-client который мы обещали считать официальным SDK, и если меняется API менять и этот клиент. Поэтому хорошо, если бы модуль для ансибля использовал именно этот клиент, а не свою реализацию общения с сервером. 
- Я как-то тоже писал подобную штуку, возможно тебе будет интересно.
Сама библиотека https://github.com/moira-alert/moira-vagrant-dev/blob/master/ansible/library/moira_trigger.py
Пример использования: https://github.com/moira-alert/moira-vagrant-dev/blob/master/ansible/moira_triggers.yml

2017-05-24 08:16 UTC, beevee requested changes
Пока комментарии только по предлагаемому синтаксису плейбука. Код не смотрел, поскольку правки потребуют существенно изменить его.

2017-05-24 08:16 UTC, beevee commented on moira_trigger.py
> +     moira-server: http://localhost/api/
В других местах в ключах используется подчеркивание, а тут дефис. Хорошо бы привести к единому виду.

2017-05-24 08:16 UTC, beevee commented on README.md
> +and 'leaves' to create different triggers based on 'branch':
Мне кажется, концепция branch/leaves дублирует уже существующую в Ansible функциональность. Обычно это делают как-то так:

```
- name: ensure moira triggers exist
  moira_trigger:
    desc: all triggers test description
    warn_value: 300
    error_value: 600
    tags: first_tag; second_tag
    ttl_state: ERROR
    name: "{{ item.name }}"
    targets: "{{ item.targets }}"
  with_items:
    - name: trigger_00
      targets: target_10.rps
    - name: trigger_01
      targets: target_11.rps
```

Дополнительная сложность мешает понимать написанное в плейбуке.

2017-05-24 08:16 UTC, beevee commented on README.md
> +         targets: target_10.rps; target_11.rps
Почему таргеты разделяются точкой с запятой? Нельзя ли сделать это обычными средствами YAML для массивов?

2017-05-24 08:16 UTC, beevee commented on README.md
> +       change:
Это неестественно для Ansible. Когда мы пишем плейбук, мы пытаемся описать целевое состояние, а не изменения. Я должен описывать желаемое состояние триггера, а модуль внутри должен понимать, нужно ли изменить какие-то теги для достижения этого состояния.

2017-05-24 08:16 UTC, beevee commented on README.md
> +       target_0: target_30.rps
То же самое. Я описываю целевое состояние триггера, а нужно ли для этого добавить/удалить таргеты, модуль внутри себя решает сам.

2017-05-26 08:09 UTC, kamaev commented on moira_trigger.py
> +     moira-server: http://localhost/api/
Окей, будет сделано

2017-05-26 08:09 UTC, kamaev commented on README.md
> +and 'leaves' to create different triggers based on 'branch':
Да, было желание просто снизить порог использования для людей не знающих jinja. Переделаю

2017-05-26 08:09 UTC, kamaev commented on README.md
> +         targets: target_10.rps; target_11.rps
Да, конечно можно. Было желание на каждый параметр уделять только одну строчку. Переделаю

2017-05-26 08:09 UTC, kamaev commented on README.md
> +       change:
Окей, переделаю

2017-05-26 08:09 UTC, kamaev commented on README.md
> +       target_0: target_30.rps
Тут есть ньюансы: начальная цель была просто удалить триггеры по определенному параметру. Более выгодным посчитал сначала удалять таргеты, а потому уже давать возможность функции подчистить все, что осталось без таргета. Иначе возникают такие вопросы:

Пусть у меня есть n триггеров, которые я хочу удалить:

при n < 10 возможно я даже не притронусь к Ansible, а просто сделаю это в вебе

10 < n < 100... получается что мне нужно иметь на руках n имён триггеров или n id триггеров, т.е. где то они должны храниться с прошлых итераций в виде лога?

Как быть если я воспользовался возможностью создания множественных таргетов в теле триггера при его сохранении, чтобы, скажем, иметь несколько групповых триггеров по разным классификациям, но в них будут повторяющиеся таргеты? Прийдется пересоздавать триггеры по новой?

*тут я - естественно не лично я, а любой пользователь

Вообще, все функции в модуле писались с расчетом на то, чтобы все необходимые действия можно было сделать одним обращением к модулю внтури одной таски.

Т.е. каким в итоге должен быть механизм удаления триггера?

2017-05-26 13:54 UTC, beevee commented on README.md
> +       target_0: target_30.rps
Удалять через ансибл будут те же триггеры, которые создавали через ансибл. Я считаю, что не нужно ставить модулю задачу управления чем-то созданным вручную.

Таким образом, удаление триггера - это проставление `state=absent` в том месте, где раньше было (или подразумевалось) `state=present`.

2017-05-31 09:26 UTC, kamaev commented on README.md
> +       target_0: target_30.rps
Upd: Модуль и документацию переписал, готовлю readme. Вечером (возможно после 21:00) будет pull request

2017-05-31 18:31 UTC, closed without merging