module itself (changed)
moira-alert/ansible-module pull request #2
Opened 2017-05-31 18:47 UTC by kamaev

2017-06-09 06:34 UTC, beevee commented
Уже можно смотреть, или ты еще доделываешь?

2017-06-09 07:16 UTC, kamaev commented
Да, конечно. Последние коммиты - это я уже сам к себе придираюсь как могу, но думаю уже в любом случае если что то ещё менять, то лучше уже на основе ревью :)

2017-06-09 12:45 UTC, beevee requested changes

2017-06-09 12:45 UTC, beevee commented on moira_trigger.py
> +        parameters_to_change = {}
По-моему, эта переменная нигде не используется.

2017-06-09 12:45 UTC, beevee commented on moira_trigger.py
> +
Ты прогонял PEP8 или какие-то линтеры? Тут, кажется, две строки должно быть между верхнеуровневыми функциями и классами. Если не прогонял, то прогони и исправь замечания.

2017-06-09 12:45 UTC, beevee commented on moira_trigger.py
> +            except:
Тут теряется информация о том, какой эксепшен вылетел. Можно ли использовать эту информацию в сообщении об ошибке для пользователя? Грубо говоря, чтобы он отличал no route to host от ошибки 500 со стороны апи. Даже если сейчас из клиента всегда вылетают одинаковые ошибки, которые невозможно отличить - в будущем это может измениться.

2017-06-09 12:45 UTC, beevee commented on moira_trigger.py
> +                trigger_id = moira_trigger.id
Тут сразу можно return делать, не просматривать остальные триггеры.

2017-06-09 12:45 UTC, beevee commented on moira_trigger.py
> +            if current_id:
Лучше явно проверять is not None, мне кажется.

2017-06-09 12:45 UTC, beevee commented on moira_trigger.py
> +            if current_id:
Тут тоже.

2017-06-09 12:45 UTC, beevee commented on moira_trigger.py
> +    moira_ansible.triggers(trigger, module.params['state'])
А тут ничего не может сломаться? Кажется, никак не проверяется, удачно ли обновился триггер.

2017-06-09 12:45 UTC, beevee commented on moira_trigger.py
> +    moira_ansible.tag_cleanup()
Тут тоже.

2017-06-09 12:45 UTC, beevee commented on moira_trigger.py
> +    def triggers(self, trigger, state):
Неудачное имя для функции. Нет никакого глагола.

2017-06-12 19:08 UTC, kamaev commented on moira_trigger.py
> +            except:
Добавил exception_handler() и запись в failed через него

2017-06-12 19:08 UTC, kamaev commented on moira_trigger.py
> +                trigger_id = moira_trigger.id
Исправил

2017-06-12 19:09 UTC, kamaev commented on moira_trigger.py
> +        parameters_to_change = {}
Убрал переменную. Спасибо! Как то совсем не обратил внимания на эту наркоманию

2017-06-12 19:11 UTC, kamaev commented on moira_trigger.py
> +    def triggers(self, trigger, state):
Переименовал функцию в 'trigger_customize'

2017-06-12 19:11 UTC, kamaev commented on moira_trigger.py
> +            if current_id:
Исправил

2017-06-12 19:12 UTC, kamaev commented on moira_trigger.py
> +            if current_id:
Исправил

2017-06-12 19:14 UTC, kamaev commented on moira_trigger.py
> +
Прогнал через pep8, pyflakes, flake8, pylint. Внёс правки за исключением конфликтующих с требованиями Ansible для импортирования модулей после RETURNS (https://docs.ansible.com/ansible/dev_guide/developing_modules_documenting.html)

2017-06-12 19:23 UTC, kamaev commented on moira_trigger.py
> +    moira_ansible.triggers(trigger, module.params['state'])
Добавил функцию 'trigger_update_check' для проверки, и изменил зависимости успешного/неуспешного выхода из модуля

2017-06-12 19:29 UTC, kamaev commented on moira_trigger.py
> +    moira_ansible.tag_cleanup()
Добавил warning для неудачного завершения 'tag_cleanup', т.к. ф-ция выполняется уже после попытки изменить состояния триггера, при неудачном выполнении которого в любом случае должен вылететь failed, в случае если состояние триггера было удачно изменено, но тэги не потерлись также будет warning (с сообщением о том, что теги могут быть потерты на следующем запуске плейбука)

2017-06-14 07:35 UTC, beevee approved these changes

2017-06-14 07:36 UTC, beevee commented
Мне норм. Ты как-то тестировал этот модуль? Работает хоть? :)

2017-06-14 07:47 UTC, merged

2017-06-20 07:50 UTC, kamaev commented
Да, прогонял на moira-vagrant-dev.
Сами тесты пока переписываю с учетом того, чтобы можно было их и для Travis использовать и в качестве поддержки модулем Dry Runs.